# Generated by Django 2.2.5 on 2019-09-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
