# Generated by Django 2.2.5 on 2019-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auth_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
