# Generated by Django 2.2.5 on 2019-10-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_auth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('author_name', models.CharField(max_length=50)),
            ],
        ),
    ]
