# Generated by Django 2.2.5 on 2019-10-03 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_reviews',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='auth_id',
        ),
        migrations.RemoveField(
            model_name='blog_reviews',
            name='link',
        ),
        migrations.AddField(
            model_name='blog_reviews',
            name='blog',
            field=models.ForeignKey(default=None, on_delete='cascade', to='blog.Blog'),
        ),
        migrations.AddField(
            model_name='blog_reviews',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
