# Generated by Django 2.2.5 on 2019-10-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191004_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_reviews',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
