# Generated by Django 2.2.5 on 2019-10-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191004_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_reviews',
            name='author',
        ),
        migrations.AddField(
            model_name='blog_reviews',
            name='author_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
