# Generated by Django 2.2.5 on 2019-10-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191004_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='blog_reviews',
            options={'verbose_name': 'Blog_reviews', 'verbose_name_plural': 'Blog_reviews'},
        ),
    ]
