# Generated by Django 2.2.5 on 2019-10-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20191005_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_reviews',
            old_name='text',
            new_name='comment',
        ),
    ]
